---
title: "Example of edge cases"
output: rmarkdown::html_vignette
author: "Qu Tang"
date: "Jul 03, 2018"
vignette: >
  %\VignetteIndexEntry{pkgdown}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(magrittr)
require(dygraphs)
```

### When maxed-out region lasts to the end of time

Bouts at the edge region (unable to do extrapolation) will be marked with __-1__.

```{r, include=FALSE, warning=FALSE}
wd = getwd()
if(stringr::str_detect(wd, "articles")){
  file_path = normalizePath(file.path(wd, "../../vignettes/data/end_edge_case_long.csv"))
}else{
  file_path = normalizePath(file.path(wd, "../vignettes/data/end_edge_case_long.csv"))
}
options(digits.secs=3)
```

```{r load_data_long, warning=FALSE, message=FALSE, include=FALSE}
df = MIMSunit::import_mhealth_csv(filepath=file_path)
```

#### Input data
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=2.5, fig.width=8.5}
require(dygraphs)
df_xts = xts::xts(df[,2:4], df[,1])
dygraphs::dygraph(df_xts) %>% dygraphs::dyRangeSelector() %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set2")) %>% dyLegend(width = 400) %>% dyAxis("y", label = "Acceleration (g)", valueRange = c(-10, 10))
```

```r
mims = MIMSunit::mims_unit(df, epoch = '5 sec', dynamic_range = c(-6, 6), output_mims_per_axis = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
mims = MIMSunit::mims_unit(df, epoch = '5 sec', dynamic_range = c(-6, 6), output_mims_per_axis = TRUE)
```

#### Output: MIMS unit values
```{r, echo=FALSE, fig.height=2.5, fig.width=8.5, message=FALSE, warning=FALSE}
mims_xts = xts::xts(mims[,2:5], mims[,1])
dygraphs::dygraph(mims_xts) %>% dygraphs::dyRangeSelector() %>% dyOptions(colors = RColorBrewer::brewer.pal(4, "Set2"), drawPoints=TRUE, pointSize=2) %>% dyLegend(width = 400) %>% dyAxis("y", label = "MIMS unit")
```
