---
title: "Quick start to use MIMSunit"
output: rmarkdown::html_vignette
author: "Qu Tang"
date: "November 21, 2017"
vignette: >
  %\VignetteIndexEntry{pkgdown}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(magrittr)
require(dygraphs)
```

### Make sure you prepare your raw accelerometer data in following csv format

```
HEADER_TIME_STAMP,X,Y,Z
2016-10-03 14:51:14.236,0.007,-0.005,0.984
2016-10-03 14:51:14.256,0.008,-0.007,0.981
2016-10-03 14:51:14.276,0.009,-0.006,0.978
2016-10-03 14:51:14.297,0.009,-0.007,0.984
2016-10-03 14:51:14.317,0.010,-0.010,0.982
2016-10-03 14:51:14.337,0.011,-0.010,0.982
```

### Load into memory using [`mHealthR`](https://qutang.github.io/mHealthR/) package

```{r, include=FALSE, warning=FALSE}
wd = getwd()
if(stringr::str_detect(wd, "articles")){
  file_path = normalizePath(file.path(wd, "../../vignettes/data/shaker.csv"))
}else{
  file_path = normalizePath(file.path(wd, "../vignettes/data/shaker.csv"))
}
options(digits.secs=3)
```

```{r load_data, warning=FALSE, message=FALSE}
df = mHealthR::mhealth.read(file_path, filetype='sensor')
```

```{r, echo=FALSE}
knitr::kable(head(df, 5))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=2.5, fig.width=8.5}
require(dygraphs)
df_xts = xts::xts(df[,2:4], df[,1])
dygraphs::dygraph(df_xts) %>% dygraphs::dyRangeSelector() %>% dyOptions(colors = RColorBrewer::brewer.pal(3, "Set2")) %>% dyLegend(width = 400)
```

### Run MIMS-unit algorithm on input data

```r
mims = MIMSunit::mims_unit(df, breaks = '1 min', range = c(-2, 2))
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
mims = MIMSunit::mims_unit(df, breaks = '5 sec', range = c(-2, 2), output_per_axis = TRUE)
```

```{r, echo=FALSE}
knitr::kable(head(mims, 5))
```

```{r, echo=FALSE, fig.height=2.5, fig.width=8.5, message=FALSE, warning=FALSE}
mims_xts = xts::xts(mims[,2:5], mims[,1])
dygraphs::dygraph(mims_xts) %>% dygraphs::dyRangeSelector() %>% dyOptions(colors = RColorBrewer::brewer.pal(4, "Set2")) %>% dyLegend(width = 400) %>% dyAxis("y", valueRange = c(0, 2 * max(mims_xts)))
```