on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '3.6'}
          - {os: windows-latest, r: 'devel'}
          - {os: macOS-latest, r: '3.6'}
         # - {os: macOS-latest, r: 'devel'}
          - {os: ubuntu-latest, r: '3.6'}
          - {os: ubuntu-latest, r: 'devel'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libxml2-dev libssl-dev libcurl4-openssl-dev libgit2-dev
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
          Rscript -e "install.packages('devtools')"
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      - name: Install dependencies
        run: |
          renv::install()
        shell: Rscript {0}

      - name: Check
        run: |
          remotes::install_cran("rcmdcheck")
          devtools::document(roclets = c('rd', 'collate', 'namespace', 'vignette'))
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check